env_name: Walker2d-v5
agent_name: LeggedRobot
experiment_name: test  # Name of the experiment
max_episodes: 300
render: True
generations: 120 # Number of generations for each population in the evolution before the next migration
neat_config: config-neat.ini
migration_steps: 4
seed: 126921842
multiple_experiments: True
