env_name: Walker2d-v4
agent_name: LeggedRobot
experiment_name: test  # Name of the experiment
max_episodes: 300
render: True
generations: 50 # Number of generations for each population in the evolution before the next migration
neat_config: config-neat.ini
migration_steps: 5
