agent_name: LeggedRobot
env_name: Walker2d-v5
experiment_name: exp3
generations: 10
max_episodes: 300
migration_steps: 1
multiple_experiments: true
neat_config: config-neat.ini
render: true
seed: 5618
